### ISSUE TITLE
Settings page

### ISSUE THREAD

**Issue by posix4e** [webtimemachine/wtm2#120]
- [x] #245
- [x] allow the backend to be changed dynamically on the backend
- [x] Hide the logout screen to the settings page

**Comment by varenc** [comment]
for inspiration, look at this extension: https://chromewebstore.google.com/detail/history-trends-unlimited/pnmchffiealhkdloeffcdnbgdnedheme?pli=1


It doesn't have perms to inject JS into every page, but it can still log all your history via the `history` permission and direct access to Chrome's own history in that way. Personally I like that permissioning model more since it requires less trust and has fewer concerns about performance/bloat from injected JS (which might be a non-issue though)
